### ISSUE TITLE
add customers endpoint

### ISSUE THREAD

**Issue by tonysviews** [klubcoin/mv-mollie-payment#2]
create a customers endpoint to retrieve customer data

request:
`GET https://klb-staging.liquichain.io/meveo/rest/pg/v1/customers/cst_tbXE3dXzHg`

response:
```json
{
  "resource": "customer",
  "id": "cst_tbXE3dXzHg",
  "mode": "test",
  "name": "netpower test",
  "email": "chuong.phan@netpower.no",
  "locale": null,
  "metadata": {
    "user_id": 2
  },
  "createdAt": "2022-04-26T07:07:43+00:00",
  "_links": {
    "self": {
      "href": "https:\/\/api.mollie.com\/v2\/customers\/cst_tbXE3dXzHg",
      "type": "application\/hal+json"
    },
    "dashboard": {
      "href": "https:\/\/www.mollie.com\/dashboard\/org_15108779\/customers\/cst_tbXE3dXzHg",
      "type": "text\/html"
    },
    "payments": {
      "href": "https:\/\/api.mollie.com\/v2\/customers\/cst_tbXE3dXzHg\/payments",
      "type": "application\/hal+json"
    },
    "documentation": {
      "href": "https:\/\/docs.mollie.com\/reference\/v2\/customers-api\/get-customer",
      "type": "text\/html"
    }
  }
}
```

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.40
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`QA Done`"  Will be closed once retested and Passed on Prod Build.

**Comment by johncalado** [comment]
Closing the ticket as already deployed and implemented on Prod Environment as well as released to Stores
