### ISSUE TITLE
[STAGING] Need API payment with id verify 

### ISSUE THREAD

**Issue by thangtrannetpower** [klubcoin/mv-mollie-payment#5]
https://api.mollie.com/v2/payments/tr_ETa4nEz4SX
Bearer: test_AGe7SgPjruuPjdC4ytwFNRswK36QV9

{"resource":"payment","id":"tr_ETa4nEz4SX","mode":"test","createdAt":"2022-05-05T04:08:17+00:00","amount":{"value":"180.00","currency":"USD"},"description":"Order 31","method":"creditcard","metadata":null,"status":"open","isCancelable":false,"expiresAt":"2022-05-05T04:25:17+00:00","locale":"en_US","countryCode":"VN","profileId":"pfl_DPAPUndvEy","customerId":"cst_tbXE3dXzHg","orderId":"ord_cg37wc","sequenceType":"oneoff","redirectUrl":"https://myknowledgemap.org/checkout/order-received/31/?key=wc_order_ImILfj6q7KyHH\u0026order_id=31\u0026filter_flag=onMollieReturn","settlementAmount":{"value":"164.44","currency":"EUR"},"details":{"cardToken":"tkn_uP8Fsvtest","cardSecurity":"3dsecure"},"_links":{"self":{"href":"https://api.mollie.com/v2/payments/tr_ETa4nEz4SX","type":"application/hal+json"},"checkout":{"href":"https://www.mollie.com/checkout/test-mode?method=creditcard\u0026token=3.injybk","type":"text/html"},"dashboard":{"href":"https://www.mollie.com/dashboard/org_15108779/payments/tr_ETa4nEz4SX","type":"text/html"},"customer":{"href":"https://api.mollie.com/v2/customers/cst_tbXE3dXzHg","type":"application/hal+json"},"order":{"href":"https://api.mollie.com/v2/orders/ord_cg37wc","type":"application/hal+json"},"documentation":{"href":"https://docs.mollie.com/reference/v2/payments-api/get-payment","type":"text/html"}}}

This is data that we need to response

**Comment by tonysviews** [comment]
@thangtrannetpower - please check if this is sufficiently implemented on staging server

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** PreProd Environment
**Fix Version:** 1.0.0.42
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`QA Done`" This fix is now ready to be deployed on Prod Env and will be closed once retested and Passed on Prod Build.

**Comment by johncalado** [comment]
Closing this ticket as already deployed to Prod and released to Stores
